#!/bin/sh

INITD='/etc/init.d/netdata'
SRCURL='https://github.com/openwrt/packages/blob/master/admin/netdata/files/netdata.init'

[ "$(sed -n '/start_service/,/}/ {/luci_overridden/p}' "$INITD")" == "" ] || exit 0


sed -i "2i# Raw file: $SRCURL" "$INITD"

sed -Ei "/start_service/a\\
\tluci_overridden\n\
\tnetdata_stop\n\
\tconfig_load 'netdata'\n\
\tconfig_foreach get_config 'netdata'\n\
\t[ \"\\\$enabled\" == \"1\" ] \|\| return 1\n\
\t[ \"\\\$ssl\" == \"1\" ] \&\& write_nginx\n\
\tlogger -t netdata -p warn \"netdata is start.\"\
" "$INITD"

sed -Ei "/start_service/,/\}/{ \
s,(procd_set_param command .+),\1 -p \\\$port\n\
\t[ \"\\\$logger\" == \"1\" ] \&\& \\\\\n\
\tprocd_set_param stdout 1 \&\& \\\\\n\
\tprocd_set_param stderr 1, \
}" "$INITD"

cat <<-"EOF" >> "$INITD"

luci_overridden() {
    return 0
}

get_config() {
    config_get_bool enabled $1 enabled 0
    config_get_bool ssl $1 ssl_sw 0
    config_get_bool auth $1 auth 0
    config_get userpw $1 userpw 'admin:$apr1$t7qQjoqb$YBHtAb7VGSkjIdObMG.Oy0'
    config_get_bool logger $1 logger 0
    config_get port $1 port 19999
}

write_nginx() {
confdir="/etc/nginx/conf.d"
location="$confdir/netdata.locations"
htpasswd="$confdir/netdata.htpasswd"
mkdir -p     "$confdir"/ 2>/dev/null
mkdir -p /var"$confdir"/ 2>/dev/null
touch "/var$location"
touch "/var$htpasswd"
[ -n "$(ls -l "$location" 2>/dev/null|grep "$location -> /var$location")" ] || ln -sf "/var$location" "$location"
[ -n "$(ls -l "$htpasswd" 2>/dev/null|grep "$htpasswd -> /var$htpasswd")" ] || ln -sf "/var$htpasswd" "$htpasswd"

echo "$userpw" > "$htpasswd"
cat << LOCATIONS > "$location"
location /netdata/ {
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_pass http://localhost:$port/;
}
LOCATIONS
if [ "$auth" == "1" ]; then
sed -i "/proxy_pass/a\\
\tauth_basic \"Please login to continue\";\n\
\tauth_basic_user_file \"$htpasswd\";\
" "$location"
fi
/etc/init.d/nginx reload
}

netdata_stop() {
    pgrep -f /usr/sbin/netdata | xargs kill -9 >/dev/null 2>&1 
    logger -t netdata -p warn "netdata is stop."
}

stop_service() {
    netdata_stop
}

service_triggers() {
    procd_add_reload_trigger 'netdata'
}
EOF
sed -Ei "s|    |\t|g" "$INITD"

pgrep -f /usr/sbin/netdata | xargs kill -9 >/dev/null 2>&1

exit 0
